trigger:
  - main 

pool:
  name: 'Default'  # Default pool with self-hosted agent NIBC2037
  demands:
    - agent.name -equals NIBC2037

steps:
  - checkout: self
    displayName: 'Checkout Code from Azure Repository'

  # Run TestComplete tests
  - script: |
      set "testCompletePath=C:\Program Files (x86)\SmartBear\TestComplete 15\Bin\TestComplete.exe"
      set "projectPath=%AGENT_WORKFOLDER%\s\TestCompleteProject\TestCompleteProject.pjs"
      
      if exist "%testCompletePath%" (
          echo Running TestComplete with project: "%projectPath%"
          "%testCompletePath%" "%projectPath%" /run /SilentMode /exit
          set exitCode=%errorlevel%
          echo Exit code: %exitCode%
          exit /b %exitCode%
      ) else (
          echo TestComplete executable not found at path: "%testCompletePath%"
          exit /b 1
      )
    displayName: 'Run TestComplete Tests'

  # Publish Test Results
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/TestResults/*.xml'
      failTaskOnFailedTests: true
    displayName: 'Publish Test Results'
