trigger:
- main 

steps:
  - checkout: self
    displayName: 'Checkout Code from azure Repository'

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
    displayName: 'Use Python 3.x'

  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        Write-Host "Running TestComplete tests..."
        # Run the TestComplete project using TestComplete CLI
        & "C:\Program Files (x86)\SmartBear\TestComplete 15\Bin\TestComplete.exe" `
          "C:\agent\_work\1\s\TestCompleteProject\TestCompleteProject.pjs" /run /SilentMode /exit
    displayName: 'Run TestComplete Tests'

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/TestResults/*.xml'
      failTaskOnFailedTests: true
    displayName: 'Publish Test Results'
