trigger:
- main 

pool:
  name: 'Default'

  
steps:
  - checkout: self
    displayName: 'Checkout Code from azure Repository'

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
    displayName: 'Use Python 3.x'

  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        Write-Host "Starting TestComplete..."
        $testCompletePath = "C:\Program Files (x86)\SmartBear\TestComplete 15\Bin\TestComplete.exe"
        $projectPath = "C:\agent\_work\1\s\TestCompleteProject\TestCompleteProject.pjs"

        if (Test-Path $testCompletePath) {
            Write-Host "Running TestComplete with project: $projectPath"
            Start-Process -FilePath $testCompletePath -ArgumentList "$projectPath /run /SilentMode /exit /NoGui"

        } else {
            Write-Host "TestComplete executable not found at path: $testCompletePath"
        }
    displayName: 'Run TestComplete Tests'


  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/TestResults/*.xml'
      failTaskOnFailedTests: true
    displayName: 'Publish Test Results'
