trigger:
  branches:
    include:
      - eggplant  # Trigger on changes to the 'eggplant' branch

pool:
  name: 'EggPlant'  # Specify the pool name for your self-hosted agent

stages:
  - stage: ExecuteBatchFile
    displayName: 'Execute Batch File'
    jobs:
      - job: RunBatchFile
        displayName: 'Run Batch File'
        steps:
          # Step 1: Check domain connectivity
          - script: |
              echo "Checking domain connectivity..."
              systeminfo | findstr /B /C:"Domain"
            displayName: 'Check Domain Connectivity'
          
          
          - script: |
              echo "Starting batch file execution as domain user somashekhard@nousinfo.com..."
              echo Cant_Drive55 | runas /user:nousinfo\somashekhard "C:\IDQ-Automation-EggPlant\Test.bat"
            displayName: 'Run Batch File as Domain User'
            failOnStderr: true  # Fail the job if there are errors

          
          - script: |
              echo "Batch file execution completed."
            displayName: 'Completion Message'