name: TestComplete CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  testcomplete:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run TestComplete Tests
        shell: pwsh
        run: |
          $testCompletePath = "C:\Program Files (x86)\SmartBear\TestComplete 15\Bin\TestComplete.exe"
          $projectPath = "${{ github.workspace }}\TestCompleteProject.pjs"

          if (Test-Path $testCompletePath) {
              & "$testCompletePath" "$projectPath" /run /exit
          } else {
              Write-Host "TestComplete executable not found."
              exit 1
          }

      - name: Publish Test Results
        uses: actions/upload-artifact@v3
        with:
          name: TestResults
          path: '**/TestResults/*.xml'
