name: TestComplete CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  testcomplete:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run TestComplete Tests
        shell: powershell
        run: |
          # Define paths for TestComplete and the correct project file path
          $testCompletePath = "C:\Program Files (x86)\SmartBear\TestComplete 15\Bin\TestComplete.exe"
          $projectPath = "C:\actions-runner\_work\TestCompleteProject\TestCompleteProject\TestCompleteProject\TestCompleteProject.pjs"

          # Log paths to check if they are correct
          Write-Host "TestComplete Path: $testCompletePath"
          Write-Host "Project Path: $projectPath"

          # Check if TestComplete exists at the specified path
          if (Test-Path $testCompletePath) {
              Write-Host "Launching TestComplete with project: $projectPath"
              
              # Run TestComplete with /run and /exit flags, and log output to a file
              & "$testCompletePath" "$projectPath" /run /exit /log "C:\TestCompleteLog.txt"
              
              # Check if the execution was successful (using exit code)
              if ($LASTEXITCODE -ne 0) {
                  Write-Host "TestComplete execution failed with exit code $LASTEXITCODE"
                  exit $LASTEXITCODE
              }
          } else {
              Write-Host "TestComplete executable not found at: $testCompletePath"
              exit 1
          }

      - name: Publish Test Results
        uses: actions/upload-artifact@v3
        with:
          name: TestResults
          path: '**/TestResults/*.xml'
          
      - name: Upload TestComplete Logs
        uses: actions/upload-artifact@v3
        with:
          name: TestComplete Logs
          path: 'C:\TestCompleteLog.txt'
