name: Run TestComplete Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  testcomplete-execution:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set Up TestComplete Environment
      - name: Set Up TestComplete
        shell: pwsh
        run: |
          Write-Host "Verifying TestComplete Installation..."
          $testCompletePath = "C:\Program Files (x86)\SmartBear\TestComplete 15\Bin\TestComplete.exe"
          if (-Not (Test-Path $testCompletePath)) {
            Write-Host "TestComplete is not installed at $testCompletePath"
            exit 1
          }
          Write-Host "TestComplete is installed and ready to use."

      # Step 3: Run TestComplete Tests
      - name: Run TestComplete
        shell: pwsh
        run: |
          $testCompletePath = "C:\Program Files (x86)\SmartBear\TestComplete 15\Bin\TestComplete.exe"
          $projectPath = "C:\actions-runner\_work\TestCompleteProject\TestCompleteProject\TestCompleteProject\TestCompleteProject.pjs"
          
          Write-Host "Launching TestComplete with project: $projectPath"
          Start-Process -FilePath $testCompletePath -ArgumentList "$projectPath /run /SilentMode /exit" -Wait -NoNewWindow

          if ($LASTEXITCODE -ne 0) {
            Write-Host "TestComplete execution failed with exit code $LASTEXITCODE"
            Write-Host "Check the log file for more details: C:\TestCompleteLog.txt"
            exit 1
          } else {
            Write-Host "TestComplete execution succeeded!"
          }

      # Step 4: Publish Test Results
      - name: Publish Test Results
        uses: actions/upload-artifact@v3
        with:
          name: TestComplete-Results
          path: C:\TestCompleteLog.txt

      # Step 5: Cleanup
      - name: Cleanup Temporary Files
        shell: pwsh
        run: |
          Write-Host "Cleaning up temporary files and logs..."
          Remove-Item -Path "C:\TestCompleteLog.txt" -ErrorAction SilentlyContinue
          Write-Host "Cleanup complete!"
